### ISSUE TITLE
IT System === Subdomain?

### ISSUE THREAD

**Issue by cremich** [ddd-crew/core-domain-charts#13]
Hey @NTCoding !

I read your article "Legacy Architecture Modernisation With Strategic Domain-Driven Design". While reading the chapter "IT Portfolio Strategy" some question arised, I already had during my first usage of the core domain chart.

In the legend, the red dots are named as subdomains. While using the core domain chart for our IT portfolio strategy we add all our IT systems. Wouldn't it be more explicit if we name the red dot in the legend with "IT System" instead of subdomain?

If I think about the systems in my current working environemt there are systems that provides solutions for multiple subdomains. For example there is a mobile app developed by a product-aligned cross functional team. This app implements B2C features along multiple subdomains. 

I am struggling a bit, what we want to visualize with a core domain chart. Is it the strategic position of a single subdomain or is it the strategic position of a IT systems? Or is it both?

Best,
Christian

**Comment by NTCoding** [comment]
Hey @cremich.

Excellent questions and observations.

I show a variety of "things" on the core domain charts. It depends on the context and level of precision. Sub-domains, bounded contexts, IT applications, even features are valid items to show on the chart.

I also group items either using colour coding or overlays to show super-contexts, team boundaries, tribes etc.

Cheers
