### ISSUE TITLE
There is no discussion of the difference between Bounded Context

### ISSUE THREAD

**Issue by ksouf** [ddd-crew/core-domain-charts#16]
I think the value of the chart can be maximized if we can integrate both of sub-domains and Bounded Context.
when starting in most cases Bounded Context ==  projections of Subdomains in solution space.
But with time some patterns like Generic Bounded Context, ...

what do you think? does it sound right to you?

**Comment by NTCoding** [comment]
Hi @ksouf.

Yeah, it makes sense to use the diagram to show either or both depending on the story you want to tell. If the BCs and subdomains are different then I can be useful to highlight that.
