### ISSUE TITLE
What's the difference between an 'outsourced/purchased' generic subdomain, and a 'platform' generic subdomain?

### ISSUE THREAD

**Issue by samlevin** [ddd-crew/core-domain-charts#18]
At first glance, the two don't seem mutually exclusive

**Comment by NTCoding** [comment]
@samlevin Good observation. They don't have to be exclusive. A platform can be a curated set of services, APIs which can be in-house or externally-purchased.

Evan Bottcher's [writing on platforms](https://martinfowler.com/articles/talk-about-platforms.html) and Team Topologies [platform content](https://teamtopologies.com/key-concepts-content/what-is-a-thinnest-viable-platform-tvp) both talk about this in more detail.

When creating a core domain chart the idea is to create notation that makes sense in your context. I've made a habit of using rod dots with a white ring my notation for current stage, but it can be anything you want. Now you've pointed this out, I think it's worth changing the image in the readme.

Thanks for that. If you have any other good ideas keep them coming.
