### ISSUE TITLE
Add explanation of "Big-bet-subdomain" and "Platform-Subdomain"

### ISSUE THREAD

**Issue by cremich** [ddd-crew/core-domain-charts#4]
Hey ddd-crew,

I am preparing some modeling sessions based on the strategic DDD template. A bit unclear for me right now is the definition of a "big-bet-subdomain" and a "platform-subdomain". 

Could you help me to better understand those two types? How do they differentiate from a "regular" core domain (the one in red 🙂 )

Thank you!
Christian

PS: sorry if an issue is not the correct way to ask those question. I was a bit unsure in this case.

**Comment by NTCoding** [comment]
Hi @cremich.

Thanks for raising this issue. I think issues are a good way to go for this type of feedback.

You highlight a good point that these things are not explained in this repo and we should do that.

In the meantime, I believe you can find answers to those questions in these blog posts:

- https://medium.com/nick-tune-tech-strategy-blog/core-domain-patterns-941f89446af5?source=collection_home---4------5-----------------------

- https://medium.com/nick-tune-tech-strategy-blog/visualising-sociotechnical-architecture-with-ddd-and-team-topologies-48c6be036c40?source=collection_home---4------3-----------------------

I'll aim to have this repo updated over the next couple of days. If you have any other suggestions or feedback of things to include, that aren't in the blog posts for example, please let me know.

**Comment by cremich** [comment]
Thanks a lot @NTCoding 

I will share my experiences with you. 

My idea is to use the core domain charts as an opener in a kickoff modeling session. My goal is to emphasize the team and the developers for the business model and strategic aspects. 
In this slot I will ask the participants to use the core-domain chart as a dot voting canvas. Each of them should put the domain onto the chart based on the individual understanding of the domain. After this we will discuss the result and aim to find a consistent classification. 

We will use this input for the next step: the bounded context canvas to mostly fill out the left side (Name, description, strategic classification) and try to clarify open questions.

Then we will have a longer break and in the afternoon continue with a event modeling session. This will hopefully help us to fill out the missing gaps in our bounded context canvas.

I am very excited to see how it works. 


I give some more details after the sessions on thursday.

**Comment by yellowbrickc** [comment]
Hi @cremich 
if I'm not mistaken, you have had your session long ago so this issue cannot be an issue anymore :)

I will close it later today if you agree.

Cheers,
Krisztina
