### ISSUE TITLE
Proposal for a "How to use" the core domain chart

### ISSUE THREAD

**Issue by cremich** [ddd-crew/core-domain-charts#6]
Hey everyone, 

I want to take the opportunity to share my experience on how I used the core-domain-charts in my recent session.

First some explanation about the context:
We did a collaborative session with devs and domain experts for a domain that is about to be created in a company. Currently it is not completely clear for everyone, whether this domain is core, supporting or generic. And I personally assumed that based on the current distribution of information, we might not have a common understanding about either the strategic classification and domain type categorization.

The first step we made in this workshop is doing some kind of a time-boxed dot-voting. Means everyone hast to pick the red circle from the notation legend and place the domain based on his current understanding in the chart. To all of the participants who are not familiar with the difference of core, supporting and generic domains, I gave a rough overview about some characteristics. Nevertheless the two axis (business differentiation and model complexity) helped a lot. 

After everyone finished, we discussed and presented the main driver for each decision. The first participant started and named the next one and so one. This raised some interesting discussions and helped to clarify the overall understanding.

In the next step, I presented the decision tree from Vladik (https://vladikk.com/2018/01/26/revisiting-the-basics-of-ddd/) and asked the participants to think about, whether they would choose a different position. And this was interesting. Some participants moved their dot into different categorizations. 

In the end we found a common understanding but still struggled a bit whether it is generic or supporting.

**Comment by cremich** [comment]
If you like the idea, maybe something for https://leanpub.com/visualcollaborationtools
:)

**Comment by NTCoding** [comment]
Thanks for sharing. Definitely sounds like a workshop recipe that others would benefit from.

**Comment by yellowbrickc** [comment]
@Baasie did you saw this real-life story and the proposal for the Visual Collaboration Tools?

**Comment by cremich** [comment]
@yellowbrickc I got already in touch with Kenny. Unfortunately did not have the time to write it down for the book. But access is already granted and I hope I find some time in the next days. ☺️

**Comment by yellowbrickc** [comment]
No problem. The link to Vladiks blog post could be still included in the starter-kit repo but as for the rest I would say, we can close this issue. What do you think?
