### ISSUE TITLE
drawio version

### ISSUE THREAD

**Issue by horsdal** [ddd-crew/core-domain-charts#9]
I made a drawio version of the core domain chart. Interested? If yes, I'd love to share it 😃

**Comment by NTCoding** [comment]
Hi @horsdal. Yes please, that would be awesome.

You could add a link in this repo and also to the virtual template repo: https://github.com/ddd-crew/virtual-modelling-templates.

If you need any help with anything please reopen the conversation and one of us will be happy to assist.
